# general.import = ["/home/steven/.config/alacritty/themes/themes/solarized_light.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/pencil_light.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/papercolor_light.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/catppuccin_latte.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/doom_one.toml"]
general.import = ["~/.config/alacritty/themes/themes/doom_one.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/doom_one.toml"]
# general.import = ["/home/steven/.config/alacritty/themes/themes/github_light.toml"]
general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
# family = "SF Mono"
# family = "Dejavu Sans Mono"
family = "CommitMono"
# family = "Hack"
# family = "Source Code Pro"
# family = "IBM Plex Mono"

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "/bin/bash"

[window]
# decorations = "none"
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
title = "Alacritty"
opacity = 0.9

[window.padding]
x = 12
y = 12
