#!/usr/bin/env zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#



launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
# From: https://github.com/koekeishiya/yabai/wiki/Configuration#window-modifications
# With focus follows mouse, you can also focus windows without having to click on them. This can be set to either autofocus (window gets focused, but not raised) or autoraise (window gets raised as if it was clicked on).
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               on
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.25
yabai -m config window_animation_duration    0.00
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.5
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Border settings
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_hidpi          on
yabai -m config window_border_blur           off
yabai -m config window_border_radius         12
# yabai -m config active_window_border_color   0xff4c7899  # i3 blue
yabai -m config active_window_border_color   0xff51afef  # doom-one blue
yabai -m config normal_window_border_color   0xff555555

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  3
yabai -m config bottom_padding               3
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   5

# label spaces
yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 7 --label 7
yabai -m space 8 --label 8
yabai -m space 9 --label 9
yabai -m space 10 --label 10
yabai -m space 11 --label 11
yabai -m space 12 --label 12
yabai -m space 13 --label 13
yabai -m space 14 --label 14
yabai -m space 15 --label 15


# float settings windows
yabai -m rule --add app='^Finder$' manage=off sticky=off
yabai -m rule --add title='Settings$' manage=off sticky=on 
yabai -m rule --add app="^System Preferences$" manage=off 
yabai -m rule --add app="^System Information$" manage=off 
yabai -m rule --add title="^Preferences$" manage=off
yabai -m rule --add title="^Digital Colour Meter$" manage=off 
yabai -m rule --add title="^General.*" manage=off   # Calendar settings
yabai -m rule --add title="^Quick Entry.*" manage=off   # Things 3 settings
yabai -m rule --add title="^Accounts.*" manage=off   # MacOS Mail accounts
yabai -m rule --add title="^Run/Debug Configurations.*" manage=off   # PyCharm
yabai -m rule --add title="^Disk Utility$" manage=off   # MacOS Disk utility
yabai -m rule --add app="^App Store$" manage=off   # MacOS App Store
yabai -m rule --add app="^Signal$" manage=off   # Signal
yabai -m rule --add app="^Messages$" manage=off   # Messages
yabai -m rule --add app="^WhatsApp$" manage=off   # WhatsApp
yabai -m rule --add app="^NordVPN$" manage=off   # NordVPN
yabai -m rule --add app="^Notes$" manage=off   # Apple Notes


# PyCharm
yabai -m rule --add title="^Merge Revisions.*" manage=off
yabai -m rule --add title="^Rename$" manage=off
yabai -m rule --add title="^Delete$" manage=off
yabai -m rule --add title="^Move$" manage=off
yabai -m rule --add title="^Copy$" manage=off
yabai -m rule --add title="^Evaluate$" manage=off
yabai -m rule --add title="^Welcome to PyCharm$" manage=off
yabai -m rule --add title="^Add File to Git$" manage=off
yabai -m rule --add title="^Emacs Everywhere.*" manage=off

# Set padding for spacebar
yabai -m config external_bar all:33:0

# Focus window to mous when windows/application is destroyed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Necessary for fyabai fork

echo "yabai configuration loaded.."
