#!/bin/sh

text=$1
curr_number=$(i3-msg -t get_workspaces  | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2 | cut -d" " -f1)
new_name=$(rofi -dmenu -lines 0 -p 'New name')

# Exit early if new_name is empty
if [ -z "$new_name" ]; then
    exit 0
fi


# Appending specific character based on workspace number
case $curr_number in
    11)
        append="(y)"
        ;;
    12)
        append="(u)"
        ;;
    13)
        append="(i)"
        ;;
    14)
        append="(o)"
        ;;
    15)
        append="(p)"
        ;;
    *)
        append=""
        ;;
esac

# Constructing the new workspace name
full_name="${curr_number} ${new_name} ${append}"

echo "current number: $curr_number"
echo "new name: $full_name"
i3-msg "rename workspace to \"$full_name\""
