#!/bin/bash

# Check if betterlockscreen is available
if command -v betterlockscreen &> /dev/null
then
    # Lock the screen using betterlockscreen with the dim effect
    betterlockscreen -l dim
else
    # Lock the screen using i3lock with a specific color
    i3lock -c 1d2026
fi

# Wait for 1 second before suspending the system
sleep 1

# Suspend the system
systemctl suspend
