#!/bin/bash

# Function to display usage
usage() {
    echo "Usage: $0 [option]"
    echo "Options:"
    echo "  idle    Save the current screen brightness and set brightness to 10%"
    echo "  resume  Set the screen brightness to previously saved value"
    echo "  h, help, -h, --help  Display this help message"
}

# Check for 'help' arguments or no arguments
if [ $# -eq 0 ] || [[ "$1" == "h" ]] || [[ "$1" == "help" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    usage
    exit 0
fi

case $1 in
    idle)
        # Save the current brightness level to a temporary file
        # brillo -q >/tmp/swaydim-last-brightness
        brillo -O
        # Set the brightness to 0%
        brillo -q -S 0 -u 150000
        ;;
    resume)
        # Restore brightness
        brillo -I -u 150000
        ;;
    *)
        echo "Invalid argument."
        usage
        exit 1
        ;;
esac
