# import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
# import = ["/home/steven/.config/alacritty/themes/themes/doom_one.toml"]
import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
live_config_reload = true

[font]
size = 19

[font.normal]
family = "CommitMono"
# family = "Hack"
# family = "Source Code Pro"
# family = "IBM Plex Mono"

[font.offset]
x = 0
y = 0

[shell]
program = "/bin/bash"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
title = "Alacritty"
opacity = 0.90

[window.padding]
x = 20
y = 20
