import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
live_config_reload = true

[font]
size = 11.0

[font.normal]
family = "Hack"

[font.offset]
x = 0
y = 0

[shell]
program = "/bin/bash"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
title = "Alacritty"
opacity = 0.9

[window.padding]
x = 5
y = 5
