# import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
general.import = ["/home/steven/.config/alacritty/themes/themes/doom_one.toml"]
# import = ["/home/steven/.config/alacritty/themes/themes/nord.toml"]
general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 19

[font.normal]
family = "CommitMono"
# family = "Hack"
# family = "Source Code Pro"
# family = "IBM Plex Mono"

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "/bin/bash"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
title = "Alacritty"
opacity = 1.00

[window.padding]
x = 16
y = 16
