[[profile]]
name = "mobile"

[[profile.output]]
enable = true
search = ["m=TL140ADXP24-0", "s=", "v=Tianma Microelectronics Ltd."]
mode = "2880x1800@60.001Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = true

[[profile]]
name = "desktop-home"

[[profile.output]]
enable = false
search = ["m=TL140ADXP24-0", "s=", "v=Tianma Microelectronics Ltd."]

[[profile.output]]
enable = true
search = ["m=LG Ultra HD", "s=0x0006462D", "v=LG Electronics"]
mode = "3840x2160@60Hz"
position = "2560,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=LU28R55", "s=HNMR100496", "v=Samsung Electric Company"]
mode = "3840x2160@60Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

[[profile]]
name = "kundes"

[[profile.output]]
enable = true
search = ["m=TL140ADXP24-0", "s=", "v=Tianma Microelectronics Ltd."]
mode = "2880x1800@120Hz"
position = "0,1440"
scale = 1.5
transform = "normal"
adaptive_sync = true

[[profile.output]]
enable = true
search = ["m=Philips UHDTV", "s=0x01010101", "v=Philips Consumer Electronics Company"]
mode = "3840x2160@60Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

[[profile]]
name = "desktop-home only left monitor"

[[profile.output]]
enable = true
search = ["m=TL140ADXP24-0", "s=", "v=Tianma Microelectronics Ltd."]
mode = "2880x1800@120Hz"
position = "3840,0"
scale = 2.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=LU28R55", "s=HNMR100496", "v=Samsung Electric Company"]
mode = "3840x2160@60Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

