#!/bin/sh

# Fetch the current workspace number
current_workspace_number=$(swaymsg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2 | cut -d" " -f1)

# Prompt for a new workspace name
new_workspace_name=$(rofi -dmenu -lines 0 -p 'New name')

# Check if the input from rofi is empty and exit early if it is
if [ -z "$new_workspace_name" ]; then
    echo "No new name provided. Exiting."
    exit 0
fi

# Function to append a specific character based on the workspace number
get_appendix_for_workspace() {
    local workspace_number=$1
    case $workspace_number in
        11) echo " (y)" ;;
        12) echo " (u)" ;;
        13) echo " (i)" ;;
        14) echo " (o)" ;;
        15) echo " (p)" ;;
        *) echo "" ;;
    esac
}

# Determine the character to append
appendix=$(get_appendix_for_workspace "$current_workspace_number")

# Construct the new workspace name
full_workspace_name="${current_workspace_number} ${new_workspace_name}${appendix}"

# Check if `niri` is running
if pgrep -x "niri" > /dev/null; then
    # If `niri` is running, use `niri` to rename the workspace
    niri msg action set-workspace-name "$full_workspace_name"
    exit 0
else
    # Rename the workspace
    swaymsg "rename workspace to \"$full_workspace_name\""
fi

