# vim: filetype=yaml
# TODO: use color aliases to make the theme more readable
---
colors:
  background:         '#2d2d2d'
  background_light:   '#5c5c5c'
  current_line:       '#393939'
  current_line_light: '#858585'
  selection:          '#515151'
  foreground:         '#cccccc'
  comment:            '#999999'
  red:                '#f2777a'
  red_light:          '#ffbdbe'
  orange:             '#f99157'
  yellow:             '#ffcc66'
  green:              '#99cc99'
  lightgreen:         '#d5f5d5'
  aqua:               '#66cccc'
  blue:               '#6699cc'
  purple:             '#cc99cc'  

meta:
  description: 'Tomorrow Night 80s theme by jmfurlott <http://jmfurlott.com>'
window_colors:
  focused:
    border:           'lightgreen'
    background:       'green'
    text:             '#000000'
    indicator:        'background'
  focused_inactive:
    border:           'current_line_light'
    background:       'current_line'
    text:             '#888888'
    indicator:        '#292d2e'
  unfocused:
    border:           'background_light'
    background:       'background'
    text:             'comment'
    indicator:        '#292d2e'
  urgent:
    border:           '#2f343a'
    background:       '#900000'
    text:             '#ffffff'
    indicator:        '#900000'
bar_colors:
  separator:          'selection'
  background:         'background'
  statusline:         'foreground'
  focused_workspace:
    border:           'lightgreen'
    background:       'green'
    text:             '#000000'
  active_workspace:
    border:           '#666666'
    background:       '#333333'
    text:             '#ffffff'
  inactive_workspace:
    border:           'background_light'
    background:       'background'
    text:             'comment'
  urgent_workspace:
    border:           'red_light'
    background:       'red'
    text:             '#ffffff'
